name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Run linting
      run: pnpm run lint:fix
      
    - name: Run formatting check
      run: pnpm run format
      
    - name: Run unit tests
      run: pnpm run test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Run integration tests
      run: pnpm run test:integration
      env:
        TEST_API_BASE_URL: ${{ secrets.TEST_API_BASE_URL }}
        TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
        TEST_ORG_ID: ${{ secrets.TEST_ORG_ID }}
        TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}