name: Tests (Python)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-lint-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        cd python
        uv sync --dev
        
    - name: Run linting with ruff
      run: |
        cd python
        uv run ruff check --fix .
        
    - name: Run formatting with ruff
      run: |
        cd python
        uv run ruff format .

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint-and-format
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-unit-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        cd python
        uv sync --dev
        
    - name: Run unit tests
      run: |
        cd python
        uv run pytest tests/ -k "not integration" -v --tb=short
      env:
        PYTHONPATH: ${{ github.workspace }}/python

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-integration-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        cd python
        uv sync --dev
        
    - name: Run integration tests
      run: |
        cd python
        uv run pytest tests/tools/ -v --tb=short
      env:
        PYTHONPATH: ${{ github.workspace }}/python
        TEST_API_BASE_URL: ${{ secrets.TEST_API_BASE_URL }}
        TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
        TEST_ORG_ID: ${{ secrets.TEST_ORG_ID }}
        TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}

  schema-generation:
    name: Schema Generation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-schema-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install Node.js dependencies
      run: pnpm install
      
    - name: Install Python dependencies
      run: |
        cd python
        uv sync --dev
        
    - name: Generate schemas
      run: pnpm run schema:build
      
    - name: Check for schema changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Schema generation produced changes!"
          git diff
          exit 1
        fi